//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int playerId { get; set; }
        public string playerName { get; set; }
        public string nationality { get; set; }
        public int playerScore { get; set; }
        public Nullable<int> wickets { get; set; }
    }
}
